name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
          xcodebuild -jobs 1 -configuration Release -arch x86_64
      - name: release
        run: |
          if [ -e ./Delivered ]; then rm -r ./Delivered; fi
          mkdir ./Delivered
          cp -RL ./Build/UninstalledProducts/macosx/ ./Delivered
          find ./Delivered -path *.DS_Store -delete
          find ./Delivered -path *.dSYM -exec echo rm -r {} \; >/tmp/org.voodoo.rm.dsym.sh
          chmod +x /tmp/org.voodoo.rm.dsym.sh
          /tmp/org.voodoo.rm.dsym.sh
          rm -Rf /tmp/org.voodoo.rm.dsym.sh
          rm -Rf ./Delivered/Debug/VoodooPS2synapticsPane.prefPane
          rm -Rf ./Delivered/Release/VoodooPS2synapticsPane.prefPane
          rm -Rf ./Delivered/Debug/synapticsconfigload
          rm -Rf ./Delivered/Release/synapticsconfigload
          ditto -c -k --sequesterRsrc --zlibCompressionLevel 9 ./Delivered ./artifact.zip
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./artifact.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true