name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: acidanthera/MacKernelSDK
          path: MacKernelSDK
      - name: 编译
        run: |
          mv VoodooPS2Controller.xcodeproj/xcuserdata/hans.xcuserdatad VoodooPS2Controller.xcodeproj/xcuserdata/${USER}.xcuserdatad
          mv VoodooPS2Controller.xcodeproj/project.xcworkspace/xcuserdata/hans.xcuserdatad VoodooPS2Controller.xcodeproj/project.xcworkspace/xcuserdata/${USER}.xcuserdatad
          make all
          make distribute
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./artifact.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true